# Site settings
title: Adrian Oniga
email: oniga.adrian.86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Looking to join the Software Testing world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adrianoniga.github.io" # the base hostname & protocol for your site
twitter_username: #
github_username:  adrianoniga
avatar: /img/adrian-oniga.png

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: 'adrianoniga'

# Build settings
markdown: kramdown
